config/routes.rb
TokyocabinetRails::Application.routes.draw do
  
  resources :records
  root :to => "records#index"

end

app/models/record.rb
require 'tokyocabinet'
include TokyoCabinet

class Record

  class << self
  
    attr_accessor :hdb
  
    def all
      perform_operation do
        records = {}
        @hdb.iterinit
        while key = @hdb.iternext
         records[key] = @hdb.get(key)
        end
        records 
      end
    end
  
    def create(key, value)
      perform_operation do
        @hdb.put(key, value)
      end
    end
  
    def perform_operation
      return if !block_given?
    
      @hdb = HDB.new
      path = File.join(Rails.root, "db/development.tch")
      @hdb.open(path, HDB::OWRITER | HDB::OCREAT)
    
      result = yield
      result == false ? report_tokyo_cabinet_error : result
    ensure
      @hdb.close
    end

    def report_tokyo_cabinet_error
      ecode = @hdb.ecode
      message = @hdb.errmsg(ecode)
      raise "Error: #{message}"
    end
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  
  def index
    @records = Record.all
  end
  
  def new
  end
  
  def create
    Record.create(params[:key], params[:value])
    redirect_to records_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TokyocabinetRails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/records/index.html.erb
<h1>All Records</h1>

<p><%= link_to 'New record', new_record_path %></p>

<% @records.each do |key, value| %>
  <p><%= key %>: <%= value %></p>
<% end %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= form_tag :action => :create do %>
  <p>
    <%= label_tag :key %>
    <%= text_field_tag :key %>
  </p>
  
  <p>
    <%= label_tag :value %>
    <%= text_field_tag :value %>
  </p>
  
  <p>
    <%= submit_tag :Create %>
  </p>
<% end %>